### ISSUE TITLE
希望支持手动输入翻译功能

### ISSUE THREAD

**Issue by yebukong** [wordway/wordway-extension#3]
![批注 2020-01-16 105020](https://user-images.githubusercontent.com/26626551/72489113-00c90500-384e-11ea-94b4-4db0302a0ded.png)
比如点击工具栏中插件按钮弹出输入框
ps:有时候单纯想查个单词，需要有一个输入单词的地方

**Comment by lijy91** [comment]
v1.0.4 已经支持，可在 Releases 下载或等待 Chrome Web Store 审核通过后更新

![image](https://user-images.githubusercontent.com/3889523/96892590-5c4eb000-14bc-11eb-8521-88c987be2596.png)
