### ISSUE TITLE
翻译浮层 展示后 滚动页面 浮层位置不符合预期

### ISSUE THREAD

**Issue by xqin** [wordway/wordway-extension#6]
翻译浮层是固定在页面中的某个位置,  在滚动时, 依然在那个位置, 但 希望它能保持在 原单词 所在的位置, 不知道有没有表述清楚.

![image](https://user-images.githubusercontent.com/1265888/72593430-e96a4480-393f-11ea-871b-50bc63f39a04.png)

**Comment by lijy91** [comment]
已经优化，请等待升级
