### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by zsakvo** [wordway/wordway-extension#7]
一个新的问题，控制台偶尔会出现如下图所示的错误，经访问后发现是本插件导致的，希望能解决下。
出现时机：不是很好把握，目前出现在某些页面的鼠标点击动作以后。

![image](https://user-images.githubusercontent.com/25399519/72692663-1e58e000-3b68-11ea-94e6-998daa7ed044.png)

**Comment by lijy91** [comment]
这个问题已经修复，请持续关注我们的后续更新

**Comment by zsakvo** [comment]
> 这个问题已经修复，请持续关注我们的后续更新

好的，感谢w
