### ISSUE TITLE
如何删除自己生词本的生词？

### ISSUE THREAD

**Issue by xyy55** [wordway/wordway-extension#8]
如题

**Comment by xyy55** [comment]
而且，网页不能看到自己的生词本吗

**Comment by lijy91** [comment]
1. 删除功能暂时存在问题，本周会更新app以支持删除生词
2. 生词本目前需要在 App 里查看

**Comment by lijy91** [comment]
v1.0.4 已增加查看生词本及翻译记录，请在 Releases 下载或等待 Chrome Web Store 审核通过后更新
![image](https://user-images.githubusercontent.com/3889523/96893160-fe6e9800-14bc-11eb-8f3c-1bfbf6cf2ab4.png)
